### ISSUE TITLE
[Feature Request] Unban audit log message

### ISSUE THREAD

**Issue by UnGameur** [submarine/Information#1]
_Hello !_
I recently restarted an old server from 0, and I wanted to remove all bans using my bot which is not in the "**ignored_users**" from modlogs.

Nevertheless, as you can see on this GIF, despite the correct channel ID, no message has been sent to me about the unban.

![tLmYj09kEJ](https://user-images.githubusercontent.com/58749382/83309384-67512d00-a209-11ea-80a5-056c6f162122.gif)

**Comment by areyouokevan** [comment]
Thanks the issue, I've added it to the roadmap!
