### ISSUE TITLE
[Feature Request] Clean: Delete invocator and response

### ISSUE THREAD

**Issue by UnGameur** [submarine/Information#2]
_Hi !_
I have just deleted a few messages but after 2 minutes, I realize that the invocator message and the bot answer have not been deleted.
![qJU2qD6EX0](https://user-images.githubusercontent.com/58749382/83328296-5a245480-a282-11ea-9fd5-8095275363df.png)

_Concerning the invocative message, I checked if it wasn't an error coming from my cache but it's not the case._

**Comment by areyouokevan** [comment]
Not a bug, Submarine doesn't automatically delete the invocator message and the bot response.
