### ISSUE TITLE
[ISSUE] « ignored_channels » not working

### ISSUE THREAD

**Issue by UnGameur** [submarine/Information#3]
_Hello,_
I noticed earlier that the "ignored_channels" value for anti-spam was not working. Submarine continues to censor and delete messages because of the spam in these channels.

_See GIF below._
![7Fex86Jm6f](https://user-images.githubusercontent.com/58749382/83761714-f7163180-a676-11ea-972c-9260cb4f8f78.gif)

**Comment by areyouokevan** [comment]
Thanks for the issue, I've added it to the roadmap, and this will likely be fixed in the coming days.

**Comment by areyouokevan** [comment]
Fixed! I'm closing the issue.
